### ISSUE TITLE
How to debug CARS if things don't work well

### ISSUE THREAD

**Issue by lionlai1989** [CNES/cars#12]
Hi:  
This project is awesome. I've encountered some issues and hope you can help.  
1. I am running CARS on a pair of Pleiades stereo imagery and the result is not very optimal. Here is CARS result:  
![Screenshot from 2022-08-12 13-51-55](https://user-images.githubusercontent.com/5163329/184348487-36042937-3f9f-484d-a1bb-68e9f12efaa4.png)

2. In the mean time, I used another open source software to run the same Pleiades data and the result is as follow:  
![Screenshot from 2022-08-12 13-50-25](https://user-images.githubusercontent.com/5163329/184348789-b05b6133-9add-4ef4-8646-04db6613c02f.png)

3. Basically, I would like to just use one software and stick to it. And I would like to understand that in this situation, what I can do to debug CARS. I am thinking checking intermediate files since CARS processes a raster by tiles. And I didn't do bundle adjustment before running. Would it help if bundle adjustment is run beforehand?  

4. I am expecting to see some intermediate files created during the processing. For example, since a raster is first split into smaller tiles, is it possible to visualize the tiled raster and see what's going on, or check the SIFT matching points?  
Thank you.

**Comment by dyoussef** [comment]
Hi @lionlai1989,

I think your issue is due to instabilities in dask mode.
I would recommend you using multiprocessing mode of compute_dsm pipeline : 
```
cars compute_dsm --mode mp --nb_workers 4
```
Also, we will present CARS 0.5.0 (Be careful, this version changes API and configuration) at FOSS4G workshop soon with information you might be interested in : https://talks.osgeo.org/foss4g-2022-workshops/talk/SFMBCR/. The materials will be available on the github.

We will keep you informed and you can also send me an e-mail for more information : david.youssefi@cnes.fr.
Regards,
David

**Comment by lionlai1989** [comment]
Hey @dyoussef :
Thanks for your reply. I am running CARS with the new API, but I found out that the new cli doesn't support either `--mode mp` or  `--nb_workers 4` arguments. I am wondering how users could provide arguments in new API? 
Thanks.

**Comment by dyoussef** [comment]
Hi @lionlai1989, with the new API, you have to provide all the arguments through the config.json file
```
{
    "inputs": {
        "sensors": {
            "one": {
                "image": "Duesseldorf/IMG_PHR1A_P_001/IMG_PHR1A_P_201807271102180_SEN_3385144101-1_R1C1.JP2",
                "geomodel": "Duesseldorf/IMG_PHR1A_P_001/RPC_PHR1A_P_201807271102180_SEN_3385144101-1.XML",
                "no_data": 0
            },
            "two": {
                "image": "Duesseldorf/IMG_PHR1A_P_002/IMG_PHR1A_P_201807271101330_SEN_3385144101-1_R1C1.JP2",
                "geomodel": "Duesseldorf/IMG_PHR1A_P_002/RPC_PHR1A_P_201807271101330_SEN_3385144101-1.XML",
                "no_data": 0
            }
        },
        "pairing": [
            [
                "one",
                "two"
            ]
        ],
        "initial_elevation": "srtm_dir"
    },
    "output": {
        "out_dir": "outresults"
    },
    "orchestrator": {
        "mode": "mp",
        "nb_workers": 4
    }
}
```
(cf. https://cars.readthedocs.io/en/latest/user_guide/configuration.html#orchestrator)

Regards,
David

**Comment by lionlai1989** [comment]
Hi @dyoussef 
I've tried your advice but there is another error and my program just hangs there without running (observed by htop). So eventually I have to use `CTRL+C` to terminate the program. Here are the step by step outputs:  
1. Run the program and it shows the following error. 
```
$ docker run -w /data -v /home/ubuntu/cars/data:/data cnes/cars /data/cars_duesseldorf_confi
g.json                                                                                                                               
Computing epipolar grids ...: 100% [**************************************************] (5s)                                         
                                                                                                                                     
Processing Tiles : [ epi_matches_left ] ...:   0%|          | 0/1886 [00:00<?, ?it/s]2022-08-24 07:31:47 (WARNING) EpipolarSparseMatc
hing: Warning: tile ignored because of the following error                                                                           itk::ExceptionObject (0x7f989c5b3a80)                                                                                                
Location: "unknown"                                                                                                                  
File: /usr/include/ITK-4.13/itkEuclideanDistanceMetric.hxx                                                                           
Line: 64                                                                                                                             
Description: itk::ERROR: EuclideanDistanceMetric(0x7f989c0b7cc0): The two measurement vectors have unequal size (128 and 2618117160) 
                                                              
2022-08-24 07:51:42 (WARNING) EpipolarSparseMatching: Warning: tile ignored because of the following error                           
itk::ExceptionObject (0x7f989c40c2b0)                                                                                                
Location: "unknown"                                                                                                                  
File: /usr/include/ITK-4.13/itkEuclideanDistanceMetric.hxx                                                                           
Line: 64                                                                                                                             
Description: itk::ERROR: EuclideanDistanceMetric(0x7f989c637a30): The two measurement vectors have unequal size (128 and 1181730355) 
                                                                                                                                     
Processing Tiles : [ epi_matches_left ] ...: 100%|██████████| 1886/1886 [29:28<00:00,  1.07it/s]                                     
Processing Tiles : [ color , dsm ] ...:   0%|          | 0/420 [00:00<?, ?it/s]Terminating: fork() called from a process already usin
g GNU OpenMP, this is unsafe.                                                                                                        
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.                                                  
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.     
```
The program hangs at this point. I observe from htop that no CPU and memory resource is being used.

2. Type CTRL+C. The output:
```
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.
^C <-- (CTRL+C IS HERE)
22-08-24 13:45:05 :: ERROR :: CARS terminated with following error
Traceback (most recent call last):
  File "/cars/venv/lib/python3.8/site-packages/cars/cars.py", line 181, in main_cli
    used_pipeline.run()
  File "/cars/venv/lib/python3.8/site-packages/cars/pipelines/sensor_to_full_resolution_dsm/sensor_to_full_resolution_dsm_pipeline.py", line 558, in run
    _ = self.rasterization_application.run(
  File "/cars/venv/lib/python3.8/site-packages/cars/orchestrator/orchestrator.py", line 314, in __exit__
    self.compute_futures()
  File "/cars/venv/lib/python3.8/site-packages/cars/orchestrator/orchestrator.py", line 253, in compute_futures
    for future_obj in self.cluster.future_iterator(future_objects):
  File "/cars/venv/lib/python3.8/site-packages/cars/orchestrator/cluster/multiprocessing_cluster.py", line 694, in __next__
    if item.ready():
KeyboardInterrupt
Processing Tiles : [ color , dsm ] ...:   0%|          | 0/420 [5:52:10<?, ?it/s]
```

Do you know what might be the problem? Thank you.

The config file:
```
{
    "inputs": {
        "sensors": {
            "one": {
                "image": "Duesseldorf/IMG_PHR1A_P_001/IMG_PHR1A_P_201807271102180_SEN_3385144101-1_R1C1.JP2",
                "geomodel": "Duesseldorf/IMG_PHR1A_P_001/RPC_PHR1A_P_201807271102180_SEN_3385144101-1.XML",
                "no_data": 0
            },
            "two": {
                "image": "Duesseldorf/IMG_PHR1A_P_002/IMG_PHR1A_P_201807271101330_SEN_3385144101-1_R1C1.JP2",
                "geomodel": "Duesseldorf/IMG_PHR1A_P_002/RPC_PHR1A_P_201807271101330_SEN_3385144101-1.XML",
                "no_data": 0
            }
        },
        "pairing": [
            [
                "one",
                "two"
            ]
        ],
        "initial_elevation": "srtm_dir"
    },
    "output": {
        "out_dir": "outresults"
    },
    "orchestrator": {
        "mode": "mp",
        "nb_workers": 16
    }
}
```

The spec of my laptop:   
- 16 CPUs  
- 64 GB memory  

Docker image: The latest `0.5.0`

**Comment by dyoussef** [comment]
Hi @lionlai1989,

Most of the people on the team are on vacation or at FOSS4G this week (me included), so we will analyse your issue next week.

We will keep you informed.
Regards,
David

**Comment by dyoussef** [comment]
Hi @lionlai1989,

https://github.com/CNES/cars/commit/5dd71e60fa8b0006b2a09ce11edc101799be3982 should fix the problem.
Can you "docker pull" cnes/cars:0.5.1 and try again ?

Thanks in advance,
David

**Comment by lionlai1989** [comment]
Hi David: 
I've tried it again. The result looks great. Thanks a lot.
![Screenshot from 2022-10-06 13-39-33](https://user-images.githubusercontent.com/5163329/194304047-302d070c-68e5-4f42-a33b-f8d1fc3e7003.png)
