### ISSUE TITLE
Insufficient amount of SIFT matches

### ISSUE THREAD

**Issue by lionlai1989** [CNES/cars#15]
Hi the team of CARS:
I am running CARS on a pair of Pleiades stereo imagery as shown below. As you can see, there are many clouds and NoData pixels in the raster.
![Screenshot from 2022-10-14 06-47-41](https://user-images.githubusercontent.com/5163329/195764733-cd5d10f8-2925-41ac-ba79-087fb93e9b23.png)

The CARS outputs the following error:
```
$ cat 22-10-11_09h16m_sensor_to_full_res_dsm.log 
22-10-11 09:22:08 :: ERROR :: Insufficient amount of matches found (< 100), can not safely estimate epipolar error correction and disparity range
22-10-11 09:27:21 :: ERROR :: CARS terminated with following error
Traceback (most recent call last):
  File "/cars/venv/lib/python3.8/site-packages/cars/cars.py", line 172, in main_cli
    used_pipeline.run()
  File "/cars/venv/lib/python3.8/site-packages/cars/pipelines/sensor_to_full_resolution_dsm/sensor_to_full_resolution_dsm_pipeline.py", line 327, in run
    matches_array = self.sparse_matching_app.filter_matches(
  File "/cars/venv/lib/python3.8/site-packages/cars/applications/sparse_matching/sift.py", line 649, in filter_matches
    raise ValueError(
ValueError: Insufficient amount of matches found (< 100), can not safely estimate epipolar error correction and disparity range
```

I checked the [source code](https://github.com/CNES/cars/blob/master/cars/applications/sparse_matching/sift.py#L643) and found that this is in the TODO list. 

My questions are:  
1. What is the rationale behind the value 100 matching points? As far as I know, 4 matching points should be sufficient to find the affine fundamental matrix? 

2.  As the above image shows, it's difficult to find matching points on cloud and water pixels and impossible on NoData pixels. And I believe that CARS is running SIFT on small tiles (500x500 pixels)? It would be great that CARS can continue the pipeline even there are insufficient matching points. Eg, let's say there are 1000 tiles in total. If there is one tile doesn't have enough SIFT points, then CARS can discard that tile and continue the rest 9999 tiles.

Thanks for reading.

**Comment by dyoussef** [comment]
Hello @lionlai1989,

We use matching points for epipolar alignement and estimate disparity range.
It is weird thaht there is less than 100 matching points : I think there is another problem.

Can you send us your data to investigate ? > david.youssefi@cnes.fr

Thanks in advance,
David

**Comment by MaxLenormand** [comment]
I've also been encountering this, I'd be curious of your findings on this issue. I'm also quite surprised about having a low number of matches and wondering what I could do about it?

I didn't find a config parameter to lower this `100` number.

**Comment by dyoussef** [comment]
We will add a config parameter to lower this 100 number : @lionlai1989 : we await your data to investigate.

**Comment by lionlai1989** [comment]
Hi:
Due to the data agreement with the data provider (Airbus), I can't send the problematic data to you. I am still trying to figure out a way to solve this. Thanks for your attention.

**Comment by lionlai1989** [comment]
> We will add a config parameter to lower this 100 number : @lionlai1989 : we await your data to investigate.
Hi:
Due to the data agreement with the data provider (Airbus), I can't send the problematic data to you. I am still trying to figure out a way to solve this. Thanks for your attention.

**Comment by dyoussef** [comment]
Can you contact us by e-mail (david.youssefi@cnes.fr) ? I think we can figure it out.

**Comment by dyoussef** [comment]
We were not able to reproduce the bug with the data we found. Perhaps you can contact the supplier so that you can transfer your exact data to us? I suggest you reopen this issue if you manage to transfer the data to us.

**Comment by dyoussef** [comment]
The homologous point detection function is set up to process 12-bit images.
Lower the peak threshold value allows to to find more points: 
```
"applications": {
    "sparse_matching": {
        "method": "sift",
        " sift_peak_threshold": 1.0
    }
},
```
